# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f613fd954b632749c2f8ccb642122867063edf6b501efbf50c5e9fadc2dfc0c7b24a738457aab193436c77e45873ba7313d7f8fb279036fd0cbe2d55cba161a

test:
  secret_key_base: 8a5312c019e676ce21889be521b720bf448251540d764d885e7a2e24d4c7324d6afe482cf3d139100cd4ee0c2b2ebdeda1ae323acc8b39acd315bc7a77d84dbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
